### ISSUE TITLE
sparse vs. compact group in LSQ-ML reconstruction

### ISSUE THREAD

**Issue by yijiang1** [AdvancedPhotonSource/tike#145]
The [least-squares solver for maximum-likelihood ptychography](https://www.osapublishing.org/oe/fulltext.cfm?uri=oe-26-3-3108&id=381198) proposed two ways to partition batches in the reconstruction: sparse and compact.
![Screen Shot 2021-07-07 at 10 36 12 AM](https://user-images.githubusercontent.com/13088588/124788716-3ca6cd00-df0f-11eb-8965-a88a4e7e350a.png)

Which method is currently in tike? Is there a plan to support both of them?

**Comment by carterbox** [comment]
The sparse partition of batches is the only method implemented in tike. There are no current plans to implement compact batches because the two methods are equivalent when the batch size includes all scan positions. In theory, including all scan positions in the batch does exceed the available memory when using multiple-gpus.

**Comment by yijiang1** [comment]
I see. That's good to know. Thanks!

**Comment by yijiang1** [comment]
A quick follow-up question: are you suggesting that I should use one full batch whenever there are enough computational resources (e.g. GPU memory)?

**Comment by carterbox** [comment]
No. I'm saying that my excuse for not implementing single GPU compact batches is that we will hopefully have enough memory on multiple GPUs.

**Comment by yijiang1** [comment]
Yeah. Even if we have enough memory to store the whole data, it may be beneficial to do reconstruction using multiple batches with a batch size smaller than the total number of diffraction patterns. Also, for some datasets, I found that compact batch can produce much better results than sparse batch.

**Comment by carterbox** [comment]
I am aware that compact batches can produce better results than sparse batches. My point is that 1 batch on multiple-GPUs is equivalent to many compact batches on a single-GPU. Do you have evidence that multiple compact batches produces better results than 1 compact batch?

**Comment by yijiang1** [comment]
> Do you have evidence that multiple compact batches produces better results than 1 compact batch?

I think so, but I'll run some tests to confirm it.

**Comment by yijiang1** [comment]
I tested several datasets and I do prefer multiple compact batches (that is, smaller batch size) for more challenging data.

**Comment by carterbox** [comment]
Could you post some comparison images here or show them at our next algorithms meeting? I'm very curious about the differences!

**Comment by yijiang1** [comment]
Yeah, I can discuss more at our meetings.

**Comment by carterbox** [comment]
Minibatches should also be more thoughtfully chosen. In the ptychoshelves comments, they seem to imply that the spare positions are random, but regularized so that they overlap as much as possible. Then the same mini-batches are used every epoch, but the order in which the minibatches are used changes each epoch.

**Comment by carterbox** [comment]
I think I already implemented this feature in the PRs mentioned above. I just need to double check.
